---
# defaults file for win_update 

- name: search and download Windows updates without installing them
  win_updates:
    category_names: 
      - SecurityUpdates
      - CriticalUpdates
      - UpdateRollups
    state: downloaded

- name: install all security, critical, and rollup updates without a scheduled task
  win_updates:
    category_names:
      - SecurityUpdates
      - CriticalUpdates
      - UpdateRollups
      register: result

# output results
- debug: var=result
    
# reboot only if required
- win_reboot:
  when: result.reboot_required