---
# tasks file for linux_mount_network_drive
# tasks file for linux_copy_file
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html

- name: copy file with owner and permissions
  ansible.builtin.copy:
    src: /etc/ansible/roles/linux_copy_file/file/test.txt
    dest: ~/
    owner: u.ansible
    group: domain/ admins
    mode: '0755'