---
# tasks file for linux_mount_network_drive
# tasks file for linux_copy_file
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html

- name: ensure required packages are installed
  apt: 
    name:
      - keyutils
      - cifs-utils
    state: present

- name: add sudo configuration for executing bash script
  lineinfile:
    path: /etc/sudoers
    line: "%#1280401187 ALL=(ALL) NOPASSWD: /bin/bash -c \"/home/mount_smb_share.sh\"" # gid gdl_barzini_authentificated_users
    state: present
    validate: '/usr/sbin/visudo -cf %s'  # Validate sudoers file syntax

- name: add sudo configuration for mount command
  lineinfile:
    path: /etc/sudoers
    line: "%#1280401187 ALL=(ALL) NOPASSWD: /bin/mount" # gid gdl_barzini_authentificated_users
    state: present
    validate: '/usr/sbin/visudo -cf %s'  # Validate sudoers file 
   
- name: copy file with owner and permissions
  ansible.builtin.copy:
    src: /etc/ansible/roles/linux_mount_network_drive/file/mount_smb_share.sh
    dest: /home/u.ansible
    owner: u.ansible
    group: gdl_barzini_authentificated_users
    mode: '0755'

#- name: create logon task for all users (run the mount script)
#  template:
#    src: /etc/ansible/roles/linux_mount_network_drive/file/logon_mnt_smb.sh.j2
#    dest: /etc/profile.d/logon_mnt_smb.sh
#    mode: '0755'
