---
# tasks file for win_mount_network_drive
# https://it-infra-ya.com/en/ansible-script_en/
# https://docs.ansible.com/ansible/latest/collections/community/windows/win_scheduled_task_module.html

- name: create task to run a custom powershell script on user logon
  community.windows.win_scheduled_task:
    name: MapNetworkDriveTask
    description: Map network drive at user logon
    actions:
    - path: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
      arguments: -ExecutionPolicy Bypass -File \\SRV-INF-001\APP_SCRIPT$\MountNetworkDrive.ps1
    triggers:
    - type: logon
    run_level: highest
    state: present
    delay: PT1M

#username: SYSTEM

 #   - name: Copy BAT file
 # win_copy:
 #   src: nfs_mount_script.bat
 #   dest: C:\nfs_mount_script.bat
