---
# tasks file for win_mount_network_drive
# https://it-infra-ya.com/en/ansible-script_en/
# https://docs.ansible.com/ansible/latest/collections/community/windows/win_scheduled_task_module.html

#- name: copy powershell script on local machine
#  win_copy:
#   src: /etc/ansible/roles/win_mount_network_drive/file/MountNetworkDrive.ps1
#   dest: C:\tmp\MountNetworkDrive.ps1
#   register: result
#   until: result is success
#   retries: 3
#   delay: 60

#- name: run a powershell script
#  win_command: powershell.exe -ExecutionPolicy ByPass -File C:\tmp\MountNetworkDrive.ps1

- name: create task to run a powershell script on user logon
  community.windows.win_scheduled_task:
    name: MapNetworkDriveTask
    description: Map network drive at user logon
    users:
      -BARZINI\Users
    actions:
    - path: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
      arguments: -ExecutionPolicy Bypass  -File C:\tmp\MountNetworkDrive.ps1
    triggers:
    - type: logon
    run_level: highest
    state: present
    delay: PT1M

