---
# tasks file for win_mount_network_drive
# https://it-infra-ya.com/en/ansible-script_en/

- name: Create task to run a custom powershell script as network service on logon
  community.windows.win_scheduled_task:
    name: MapNetworkDriveTask
    description: Map network drive at user logon
    actions:
    - path: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
      arguments: "-ExecutionPolicy Bypass -NonInteractive -File \\srv-inf-001\APP_SCRIPT$\MountNetworkDrive.ps1"
    triggers:
    - type: logon
    run_level: highest
    state: present
