---
# tasks file for linux_deploy_kontrast
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html
# https://apps.kde.org/fr/kontrast/
# https://ubuntuhandbook.org/index.php/2021/11/check-contrast-colors-ubuntu-kontrast/

  - name: update apt cache and install the latest kontrast package
    become: true
    apt: 
      name: kontrast 
      update_cache: yes
      state: latest

  - name: create an application symlink launcher on the desktop
    ansible.builtin.shell: |
      for user in /home/*
      do
        symlink_path="$user/Desktop/kontrast.desktop"
        target_path="/usr/share/applications/org.kde.kontrast.desktop"
        ln -s "$target_path" "$symlink_path"
      # make the symlink executable 
        chmod +x "$symlink_path"
      # create a desktop entry file
        desktop_entry_path="$user/Desktop/kontrast.desktop"
        desktop_entry_content="[Desktop Entry]\nName=Kontrast\nExec=$target_path\nType=Application\n"
        echo -e "$desktop_entry_content" > "$desktop_entry_path"
      done