---
# tasks file for linux_deploy_kontrast
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html
# https://apps.kde.org/fr/kontrast/
# https://ubuntuhandbook.org/index.php/2021/11/check-contrast-colors-ubuntu-kontrast/

 # - name: update apt cache and install the latest kontrast package
 #   become: true
 #   apt: 
 #     name: kontrast 
 #     update_cache: yes
 #     state: latest

  - name: create an application symlink on the desktop
    ansible.builtin.file:
      src: /usr/share/applications/org.kde.kontrast.desktop
      dest: /home/u.ansible@barzini.lan/Desktop/kontrast.desktop
      owner: u.ansible@barzini.lan
      group: domain users
      mode: '0755'
      state: link