---
# defaults file for win_update and upgrade chocolatey packages

- name: search and download Windows updates without installing them
  win_updates:
    category_names: 
      - SecurityUpdates
      - CriticalUpdates
      - UpdateRollups
    state: downloaded

- name: install all security, critical, and rollup updates 
  win_updates:
    category_names:
      - SecurityUpdates
      - CriticalUpdates
      - UpdateRollups
    state: installed
    register: update_result

# chocolatey upgrade packages
# https://docs.ansible.com/ansible/latest/collections/chocolatey/chocolatey/win_chocolatey_module.html

- name: chocolatey upgrade installed packages
  win_chocolatey:
    name: all
    state: latest

# output results
#- debug: var=result
    
# reboot only if required
#- win_reboot:
#  when: result.reboot_required

#- name: checking for missing updates
#  win_updates:
#    state: installed
#    category_names: "{{ win_updates_categories }}"
#    register: update_count